# Created by: Tobias Berner <tcberner@gmail.com>

PORTNAME=	kguiaddons
CATEGORIES=	x11-toolkits # kde-framework
COMMENT=	KDE5 gui addons

USE_QT5=	core gui widgets x11extras
USE_KDE5=	ecm kdeprefix

.include "${.CURDIR}/../../x11/kde5-frameworks/bsd.kde5-frameworks.mk"
.include <bsd.port.mk>
