# Created by: Tobias Berner <tcberner@gmail.com>

PORTNAME=	kguiaddons
CATEGORIES=	x11-toolkits # kde-framework
COMMENT=	KDE5 gui addons

USE_QT5=        x11extras core gui widgets
USE_KDE5=       kdeprefix ecm
		
.include "${.CURDIR}/../../x11/kde5-frameworks/bsd.kde5-frameworks.mk"
.include <bsd.port.mk>
