# Created by: Tobias Berner <tcberner@gmail.com>

PORTNAME=	kidletime
CATEGORIES=	devel # kde-framework
COMMENT=	KDE5 idletime

USE_QT5=        core gui widgets x11extras dbus
USE_KDE5=       kdeprefix ecm
		
.include "${.CURDIR}/../../x11/kde5-frameworks/bsd.kde5-frameworks.mk"
.include <bsd.port.mk>
