# Created by: Tobias Berner <tcberner@gmail.com>

PORTNAME=	kpty
CATEGORIES=	devel # kde-framework
COMMENT=	KDE5 kpty

USE_QT5=        core
USE_KDE5=       kdeprefix ecm coreaddons i18n

.include "${.CURDIR}/../../x11/kde5-frameworks/bsd.kde5-frameworks.mk"
.include <bsd.port.mk>
