# Created by: Tobias Berner <tcberner@gmail.com>

PORTNAME=	kdnssd
CATEGORIES=	dns # kde-framework
COMMENT=	KDE5 dnssd

USE_QT5=	core dbus linguisttools network
USE_KDE5=	ecm kdeprefix

OPTIONS_DEFINE=	NLS
OPTIONS_SUB=	YES

.include "${.CURDIR}/../../x11/kde5-frameworks/bsd.kde5-frameworks.mk"
.include <bsd.port.mk>
