# Created by: Tobias Berner <tcberner@gmail.com>

PORTNAME=	kdnssd
CATEGORIES=	dns # kde-framework
COMMENT=	KDE5 dbus addons

USE_QT5=        core network dbus linguisttools
USE_KDE5=       kdeprefix ecm
		
.include "${.CURDIR}/../../x11/kde5-frameworks/bsd.kde5-frameworks.mk"
.include <bsd.port.mk>
