# Created by: Tobias Berner <tcberner@gmail.com>

PORTNAME=       oxygen
PORTVERSION=    ${KDE5_VERSION}
CATEGORIES=     x11-themes # kde-plasma
COMMENT=        KDE5 oxygen 

USE_QT5=        xml dbus core gui widgets x11extras
USE_KDE5=       kdeprefix coreaddons dbusaddons auth codecs configwidgets    \
                itemviews iconthemes ecm i18n config guiaddons widgetsaddons \
                service completion frameworkintegration windowsystem

.include "${.CURDIR}/../../x11/kde5-plasma/bsd.kde5-plasma.mk"
.include <bsd.port.mk>

