# Created by: Tobias Berner <tcberner@gmail.com>

PORTNAME=	karchive
CATEGORIES=	archivers # kde-framework

COMMENT=	KDE5 archive

USE_QT5=	core
USE_KDE5=	ecm kdeprefix

.include "${.CURDIR}/../../x11/kde5-frameworks/bsd.kde5-frameworks.mk"
.include <bsd.port.mk>
