# Created by: Tobias Berner <tcberner@gmail.com>

PORTNAME=       ksysguard
CATEGORIES=     sysutils # kde-plasma
COMMENT=        KDE5 ksysguard 

USE_QT5=        xml dbus network printsupport core gui widgets
USE_KDE5=       kdeprefix archive auth codecs guiaddons widgetsaddons   \
                configwidgets globalaccel completion dbusaddons service \
                windowsystem sonnet textwidgets attica xmlgui bookmarks \
                jobwidgets solid kio crash designerplugin doctools      \
                emoticons itemmodels init notifications parts           \
                unitconversion kdelibs4support ecm coreaddons i18n      \
                itemviews newstuff config iconthemes libksysguard

.include "${.CURDIR}/../../x11/kde5-plasma/bsd.kde5-plasma.mk"
.include <bsd.port.mk>

