# Created by: Tobias Berner <tcberner@gmail.com>

PORTNAME=       powerdevil
CATEGORIES=     sysutils # kde-plasma
COMMENT=        KDE5 powerdevil 

USE_QT5=        xml network printsupport gui widgets dbus x11extras core
USE_KDE5=       kdeprefix coreaddons codecs guiaddons widgetsaddons \
                configwidgets itemviews iconthemes completion dbusaddons \
                service sonnet textwidgets attica xmlgui bookmarks jobwidgets \
                crash designerplugin archive doctools emoticons itemmodels init  \
                notifications parts unitconversion auth idletime config solid \
                i18n globalaccel kio windowsystem ecm plasma-framework notifyconfig \
                kdelibs4support
                
.include "${.CURDIR}/../../x11/kde5-plasma/bsd.kde5-plasma.mk"
.include <bsd.port.mk>

