# Created by: Tobias Berner <tcberner@gmail.com>

PORTNAME=	solid 
CATEGORIES=	devel # kde-framework
COMMENT=	KDE5 solid

USE_QT5=        core xml dbus gui widgets concurrent
USE_KDE5=       kdeprefix ecm

.include "${.CURDIR}/../../x11/kde5-frameworks/bsd.kde5-frameworks.mk"
.include <bsd.port.mk>
