# Created by: Tobias Berner <tcberner@gmail.com>

PORTNAME=	solid 
CATEGORIES=	devel # kde-framework
COMMENT=	KDE5 solid

USE_QT5=	concurrent core dbus gui linguisttools qml widgets xml
USE_KDE5=	ecm kdeprefix

.include "${.CURDIR}/../../x11/kde5-frameworks/bsd.kde5-frameworks.mk"
.include <bsd.port.mk>
