# Created by: Tobias Berner <tcberner@gmail.com>

PORTNAME=	kdbusaddons 
CATEGORIES=	devel # kde-framework
COMMENT=	KDE5 dbus addons

USE_QT5=        gui x11extras core dbus linguisttools testlib
USE_KDE5=       kdeprefix ecm
		
.include "${.CURDIR}/../../x11/kde5-frameworks/bsd.kde5-frameworks.mk"
.include <bsd.port.mk>
