# Created by: Tobias Berner <tcberner@gmail.com>

PORTNAME=	kdbusaddons
CATEGORIES=	devel # kde-framework
COMMENT=	KDE5 dbus addons

USE_QT5=	core dbus gui linguisttools x11extras
USE_KDE5=	ecm kdeprefix

.include "${.CURDIR}/../../x11/kde5-frameworks/bsd.kde5-frameworks.mk"
.include <bsd.port.mk>
