# Created by: Tobias Berner <tcberner@gmail.com>

PORTNAME=	kcompletion
CATEGORIES=	x11-toolkits # kde-framework
COMMENT=	KDE5 kcompletion

USE_QT5=        core gui widgets xml linguisttools
USE_KDE5=       kdeprefix ecm config widgetsaddons
		
.include "${.CURDIR}/../../x11/kde5-frameworks/bsd.kde5-frameworks.mk"
.include <bsd.port.mk>
