# Created by: Tobias Berner <tcberner@gmail.com>

PORTNAME=	kcompletion
CATEGORIES=	x11-toolkits # kde-framework
COMMENT=	KDE5 kcompletion

USE_QT5=	core gui linguisttools widgets xml
USE_KDE5=	config ecm kdeprefix widgetsaddons

.include "${.CURDIR}/../../x11/kde5-frameworks/bsd.kde5-frameworks.mk"
.include <bsd.port.mk>
