# Created by: Tobias Berner <tcberner@gmail.com>

PORTNAME=       kio-extras 
CATEGORIES=     devel # kde-plasma
COMMENT=        KDE5 kio-extras 

USE_QT5=        xml printsupport dbus network gui widgets core
USE_KDE5=       kdeprefix auth codecs guiaddons widgetsaddons itemviews \
                globalaccel completion service windowsystem sonnet      \
                textwidgets attica xmlgui bookmarks jobwidgets js       \
                notifications parts wallet crash designerplugin         \
                emoticons itemmodels init unitconversion                \
                kdelibs4support ecm archive config configwidgets        \
                coreaddons dbusaddons doctools dnssd iconthemes i18n    \
                kio khtml  solid

.include "${.CURDIR}/../../x11/kde5-plasma/bsd.kde5-plasma.mk"
.include <bsd.port.mk>

