# Created by: Tobias Berner <tcberner@gmail.com>

PORTNAME=	kio-extras 
CATEGORIES=	devel # kde-plasma
COMMENT=	KDE5 kio-extras 

USE_QT5=	core dbus gui network printsupport widgets xml
USE_KDE5=	archive attica auth bookmarks codecs completion config \
		configwidgets coreaddons crash dbusaddons designerplugin \
		dnssd doctools ecm emoticons globalaccel guiaddons i18n \
		iconthemes init itemmodels itemviews jobwidgets js \
		kdelibs4support kdeprefix khtml kio notifications parts \
		service solid sonnet textwidgets unitconversion wallet \
		widgetsaddons windowsystem xmlgui

.include "${.CURDIR}/../../x11/kde5-plasma/bsd.kde5-plasma.mk"
.include <bsd.port.mk>

