# Created by: Tobias Berner <tcberner@gmail.com>

PORTNAME=       milou 
CATEGORIES=     deskutils # kde-plasma
COMMENT=        KDE5 milou 

USE_QT5=        xml dbus script network qml gui widgets core
USE_KDE5=       kdeprefix coreaddons auth codecs config guiaddons widgetsaddons \
                configwidgets itemviews iconthemes globalaccel completion       \
                dbusaddons service windowsystem sonnet textwidgets attica       \
                xmlgui bookmarks jobwidgets solid kio runner ecm plasma-framework i18n    \
                declarative
                
.include "${.CURDIR}/../../x11/kde5-plasma/bsd.kde5-plasma.mk"
.include <bsd.port.mk>

