# Created by: Tobias Berner <tcberner@gmail.com>

PORTNAME=	milou 
CATEGORIES=	deskutils # kde-plasma
COMMENT=	KDE5 milou 

USE_QT5=	core dbus gui network qml script widgets xml
USE_KDE5=	attica auth bookmarks codecs completion config \
		configwidgets coreaddons dbusaddons declarative \
		ecm globalaccel guiaddons i18n iconthemes \
		itemviews jobwidgets kdeprefix kio plasma-framework \
		runner service solid sonnet textwidgets widgetsaddons \
		windowsystem xmlgui

.include "${.CURDIR}/../../x11/kde5-plasma/bsd.kde5-plasma.mk"
.include <bsd.port.mk>

