# Created by: Tobias Berner <tcberner@gmail.com>

PORTNAME=       kde-cli-tools
CATEGORIES=     sysutils # kde-plasma
COMMENT=        KDE5 kde-cli-tools 

USE_QT5=        x11extras xml network printsupport core gui widgets svg dbus
USE_KDE5=       kdeprefix coreaddons auth codecs guiaddons widgetsaddons	\
		configwidgets itemviews dbusaddons service globalaccel 		\
		completion sonnet textwidgets attica xmlgui pty crash 		\
		designerplugin archive doctools emoticons itemmodels init	\
		notifications bookmarks jobwidgets solid kio parts		\
		unitconversion kdelibs4support ecm config iconthemes i18n	\
		kcmutils kdesu windowsystem

.include "${.CURDIR}/../../x11/kde5-plasma/bsd.kde5-plasma.mk"
.include <bsd.port.mk>

