# Created by: Tobias Berner <tcberner@gmail.com>

PORTNAME=	kde-cli-tools
CATEGORIES=	sysutils # kde-plasma
COMMENT=	KDE5 kde-cli-tools 

USE_QT5=	core dbus gui network printsupport svg widgets x11extras xml
USE_KDE5=	archive attica auth bookmarks codecs completion config \
		configwidgets coreaddons crash dbusaddons designerplugin \
		doctools ecm emoticons globalaccel guiaddons i18n \
		iconthemes init itemmodels itemviews jobwidgets kcmutils \
		kdelibs4support kdeprefix kdesu kio notifications parts \
		pty service solid sonnet textwidgets unitconversion \
		widgetsaddons windowsystem xmlgui

.include "${.CURDIR}/../../x11/kde5-plasma/bsd.kde5-plasma.mk"
.include <bsd.port.mk>

