# Created by: Tobias Berner <tcberner@gmail.com>

PORTNAME=	kwidgetsaddons 
CATEGORIES=	x11-toolkits # kde-framework
COMMENT=	KDE5 widgets

USE_QT5=	core gui linguisttools uitools widgets
USE_KDE5=	ecm kdeprefix

.include "${.CURDIR}/../../x11/kde5-frameworks/bsd.kde5-frameworks.mk"
.include <bsd.port.mk>
