# Created by: Tobias Berner <tcberner@gmail.com>

PORTNAME=	kded
CATEGORIES=	x11 # kde-framework
COMMENT=	KDE5 kded

USE_QT5=        core dbus gui widgets xml
USE_KDE5=       kdeprefix ecm config coreaddons windowsystem\
                crash dbusaddons archive doctools init i18n service

.include "${.CURDIR}/../../x11/kde5-frameworks/bsd.kde5-frameworks.mk"
.include <bsd.port.mk>
