# Created by: Tobias Berner <tcberner@gmail.com>

PORTNAME=	attica 
CATEGORIES=	x11-toolkits # kde-framework
COMMENT=	Open Collaboration Services API library KDE5 version

USE_QT5=	core gui network widgets
USE_KDE5=	ecm kdeprefix

.include "${.CURDIR}/../../x11/kde5-frameworks/bsd.kde5-frameworks.mk"
.include <bsd.port.mk>
