# Created by: Tobias Berner <tcberner@gmail.com>

PORTNAME=	attica 
CATEGORIES=	x11-toolkits # kde-framework
COMMENT=	Open Collaboration Services API library KDE5 version

USE_QT5=        core network gui widgets
USE_KDE5=       kdeprefix ecm

.include "${.CURDIR}/../../x11/kde5-frameworks/bsd.kde5-frameworks.mk"
.include <bsd.port.mk>
