# Created by: Tobias Berner <tcberner@gmail.com>

PORTNAME=	kdewebkit
CATEGORIES=	www # kde-framework
COMMENT=	KDE5 webkit

USE_QT5=	core dbus gui network opengl printsupport qml quick webkit \
		widgets xml
USE_KDE5=	attica auth bookmarks codecs completion config configwidgets \
		coreaddons dbusaddons ecm globalaccel guiaddons i18n \
		iconthemes itemviews jobwidgets kdeprefix kio notifications \
		parts service solid sonnet textwidgets wallet widgetsaddons \
		windowsystem xmlgui

.include "${.CURDIR}/../../x11/kde5-frameworks/bsd.kde5-frameworks.mk"
.include <bsd.port.mk>
