# Created by: Tobias Berner <tcberner@gmail.com>

PORTNAME=	sonnet
CATEGORIES=	textproc # kde-framework
COMMENT=	KDE5 sonnet

USE_QT5=	core gui linguisttools widgets
USE_KDE5=	ecm kdeprefix

.include "${.CURDIR}/../../x11/kde5-frameworks/bsd.kde5-frameworks.mk"
.include <bsd.port.mk>
