# Created by: Tobias Berner <tcberner@gmail.com>

PORTNAME=	sonnet
CATEGORIES=	textproc # kde-framework
COMMENT=	KDE5 sonnet

USE_QT5=        core gui widgets linguisttools
USE_KDE5=       kdeprefix ecm
		
.include "${.CURDIR}/../../x11/kde5-frameworks/bsd.kde5-frameworks.mk"
.include <bsd.port.mk>
