# Created by: Tobias Berner <tcberner@gmail.com>

PORTNAME=       systemsettings
CATEGORIES=     sysutils # kde-plasma
COMMENT=        KDE5 systemsettings 

USE_KDE5=       kdeprefix ecm khtml
USE_QT5=        core dbus linguisttools
                
.include "${.CURDIR}/../../x11/kde5-plasma/bsd.kde5-plasma.mk"
.include <bsd.port.mk>

