# Created by: Tobias Berner <tcberner@gmail.com>

PORTNAME=	kate
CATEGORIES=	editors # kde-applications
COMMENT=	KDE5 kate
PKGNAMEPREFIX=	kde5-

USE_QT5=	core dbus script sql widgets
USE_KDE5=	config doctools ecm guiaddons i18n init jobwidgets kdeprefix \
		kio parts texteditor windowsystem xmlgui

.include "${.CURDIR}/../../x11/kde-applications/bsd.kde-applications.mk"
.include <bsd.port.mk>

