# Created by: Tobias Berner <tcberner@gmail.com>

PORTNAME=	kpackage
CATEGORIES=	devel # kde-framework
COMMENT=	KDE5 configuration framework

USE_QT5=	core gui linguisttools xml
USE_KDE5=	archive config coreaddons doctools ecm i18n kdeprefix

OPTIONS_DEFINE=	DOCS NLS
OPTIONS_SUB=	YES

.include "${.CURDIR}/../../x11/kde5-frameworks/bsd.kde5-frameworks.mk"
.include <bsd.port.mk>
