# Created by: Tobias Berner <tcberner@gmail.com>

PORTNAME=	kauth 
CATEGORIES=	devel # kde-framework
COMMENT=	KDE5 auth 

USE_QT5=        core gui linguisttools widgets dbus
USE_KDE5=       kdeprefix ecm coreaddons
		
.include "${.CURDIR}/../../x11/kde5-frameworks/bsd.kde5-frameworks.mk"
.include <bsd.port.mk>
