# Created by: Tobias Berner <tcberner@gmail.com>

PORTNAME=	kauth
CATEGORIES=	devel # kde-framework
COMMENT=	KDE5 auth

USE_QT5=	core dbus gui linguisttools polkit5 widgets
USE_KDE5=	coreaddons ecm kdeprefix

OPTIONS_DEFINE=	NLS
OPTIONS_SUB=	YES

.include "${.CURDIR}/../../x11/kde5-frameworks/bsd.kde5-frameworks.mk"
.include <bsd.port.mk>
