# Created by: Tobias Berner <tcberner@gmail.com>

PORTNAME=	kemoticons
CATEGORIES=	x11-themes # kde-framework
COMMENT=	KDE5 emoticons

USE_QT5=	core dbus gui widgets xml
USE_KDE5=	archive config coreaddons dbusaddons ecm i18n kdeprefix service

.include "${.CURDIR}/../../x11/kde5-frameworks/bsd.kde5-frameworks.mk"
.include <bsd.port.mk>
