# Created by: Tobias Berner <tcberner@gmail.com>

PORTNAME=	kemoticons
CATEGORIES=	x11-themes # kde-framework
COMMENT=	KDE5 emoticons

USE_QT5=        core gui dbus xml widgets
USE_KDE5=       kdeprefix ecm archive config coreaddons dbusaddons i18n service
		
.include "${.CURDIR}/../../x11/kde5-frameworks/bsd.kde5-frameworks.mk"
.include <bsd.port.mk>
