# Created by: Tobias Berner <tcberner@gmail.com>

PORTNAME=	ktexteditor
CATEGORIES=	devel # kde-framework
COMMENT=	KDE5 texteditor 

USE_QT5=        core gui widgets script printsupport xml dbus network
USE_KDE5=       kdeprefix ecm archive config guiaddons i18n coreaddons \
                auth codecs widgetsaddons configwidgets itemviews \
                iconthemes globalaccel completion dbusaddons service \
                windowsystem textwidgets attica xmlgui bookmarks \
                jobwidgets solid kio notifications parts sonnet		

.include "${.CURDIR}/../../x11/kde5-frameworks/bsd.kde5-frameworks.mk"
.include <bsd.port.mk>
