# Created by: Tobias Berner <tcberner@gmail.com>

PORTNAME=	ktexteditor
CATEGORIES=	devel # kde-framework
COMMENT=	KDE5 texteditor 

USE_QT5=	core dbus gui network printsupport script widgets xml
USE_KDE5=	archive attica auth bookmarks codecs completion config \
		configwidgets coreaddons dbusaddons ecm globalaccel \
		guiaddons i18n iconthemes itemviews jobwidgets kdeprefix \
		kio notifications parts service solid sonnet textwidgets \
		widgetsaddons windowsystem xmlgui

.include "${.CURDIR}/../../x11/kde5-frameworks/bsd.kde5-frameworks.mk"
.include <bsd.port.mk>
