# Created by: Tobias Berner <tcberner@gmail.com>

PORTNAME=	khotkeys
CATEGORIES=	devel # kde-plasma
COMMENT=	KDE5 khotkeys

USE_QT5=	core dbus linguisttools
USE_KDE5=	ecm itemmodels kdeprefix plasma-framework plasma-workspace

.include "${.CURDIR}/../../x11/kde5-plasma/bsd.kde5-plasma.mk"
.include <bsd.port.mk>

