# Created by: Tobias Berner <tcberner@gmail.com>

PORTNAME=       khotkeys
CATEGORIES=     devel # kde-plasma
COMMENT=        KDE5 khotkeys 

USE_KDE5=       kdeprefix ecm plasma-framework itemmodels plasma-workspace
USE_QT5=        core dbus linguisttools

.include "${.CURDIR}/../../x11/kde5-plasma/bsd.kde5-plasma.mk"
.include <bsd.port.mk>

