# Created by: Tobias Berner <tcberner@gmail.com>

PORTNAME=	plasma
PKGNAMEPREFIX?=	kde5-

CATEGORIES=	x11 # kde-plasma
PORTVERSION=	${KDE5_VERSION}

MAINTAINER=	kde@FreeBSD.org
COMMENT=	KDE5 plasma meta port

USE_KDE5=	${_USE_KDE5_PLASMA_ALL}
# TODO: run depend on it

DISTFILES=	#
NO_BUILD=	yes
NO_INSTALL=	yes
NO_MTREE=	yes

.include <bsd.port.mk>

