# Created by: Tobias Berner <tcberner@gmail.com>

PORTNAME=	ktextwidgets
CATEGORIES=	x11-toolkits # kde-framework
COMMENT=	KDE5 text widgets

USE_QT5=	core dbus gui widgets xml
USE_KDE5=	auth codecs completion config configwidgets \
		coreaddons dbusaddons ecm guiaddons i18n \
		iconthemes itemviews kdeprefix service sonnet \
		widgetsaddons windowsystem

.include "${.CURDIR}/../../x11/kde5-frameworks/bsd.kde5-frameworks.mk"
.include <bsd.port.mk>
