# Created by: Tobias Berner <tcberner@gmail.com>

PORTNAME=	ktextwidgets 
CATEGORIES=	x11-toolkits # kde-framework
COMMENT=	KDE5 text widgets

USE_QT5=        core gui widgets dbus xml
USE_KDE5=       kdeprefix ecm completion config coreaddons \
                auth codecs guiaddons configwidgets i18n   \
                itemviews iconthemes dbusaddons service    \
                widgetsaddons windowsystem sonnet

.include "${.CURDIR}/../../x11/kde5-frameworks/bsd.kde5-frameworks.mk"
.include <bsd.port.mk>
