# Created by: Tobias Berner <tcberner@gmail.com>

PORTNAME=	kdesu
CATEGORIES=	security # kde-framework
COMMENT=	KDE5 su frontend

USE_QT5=	core dbus xml
USE_KDE5=	config coreaddons dbusaddons ecm i18n kdeprefix pty service

OPTIONS_DEFINE=	NLS
OPTIONS_SUB=	YES

.include "${.CURDIR}/../../x11/kde5-frameworks/bsd.kde5-frameworks.mk"
.include <bsd.port.mk>
