# Created by: Tobias Berner <tcberner@gmail.com>

PORTNAME=	kdesu
CATEGORIES=	security # kde-framework
COMMENT=	KDE5 su frontend

USE_QT5=        core xml dbus
USE_KDE5=       kdeprefix ecm coreaddons config dbusaddons i18n service pty

.include "${.CURDIR}/../../x11/kde5-frameworks/bsd.kde5-frameworks.mk"
.include <bsd.port.mk>
