# Created by: Tobias Berner <tcberner@gmail.com>

PORTNAME=       kfilemetadata
CATEGORIES=     devel # kde-plasma
COMMENT=        KDE5 kfilemetadata 

USE_QT5=        dbus core xml
USE_KDE5=       kdeprefix config coreaddons dbusaddons ecm i18n service archive
                
.include "${.CURDIR}/../../x11/kde5-plasma/bsd.kde5-plasma.mk"
.include <bsd.port.mk>

