# Created by: Tobias Berner <tcberner@gmail.com>

PORTNAME=	kconfigwidgets 
CATEGORIES=	x11-toolkits # kde-framework
COMMENT=	KDE5 config widgets

USE_QT5=        core gui widgets dbus xml
USE_KDE5=       kdeprefix ecm auth coreaddons codecs config \
                archive doctools guiaddons i18n widgetsaddons

.include "${.CURDIR}/../../x11/kde5-frameworks/bsd.kde5-frameworks.mk"
.include <bsd.port.mk>
