# Created by: Tobias Berner <tcberner@gmail.com>

PORTNAME=	kconfigwidgets
CATEGORIES=	x11-toolkits # kde-framework
COMMENT=	KDE5 config widgets

USE_QT5=	core dbus gui widgets xml
USE_KDE5=	archive auth codecs config coreaddons doctools ecm guiaddons \
		i18n kdeprefix widgetsaddons

.include "${.CURDIR}/../../x11/kde5-frameworks/bsd.kde5-frameworks.mk"
.include <bsd.port.mk>
