# Created by: Tobias Berner <tcberner@gmail.com>

PORTNAME=	kjs
CATEGORIES=	www # kde-framework
COMMENT=	KDE5 js
MASTER_SITE_SUBDIR?=	stable/frameworks/${KDE5_FRAMEWORKS_VERSION:R}/portingAids

USE_QT5=	core
USE_KDE5=	ecm kdeprefix

.include "${.CURDIR}/../../x11/kde5-frameworks/bsd.kde5-frameworks.mk"
.include <bsd.port.mk>
