# Created by: Tobias Berner <tcberner@gmail.com>

PORTNAME=       kmenuedit
CATEGORIES=     sysutils # kde-plasma
COMMENT=        KDE5 kmenuedit 

USE_QT5=        gui widgets network printsupport core dbus xml
USE_KDE5=       kdeprefix config coreaddons auth codecs guiaddons  \
                widgetsaddons configwidgets globalaccel itemviews  \
                completion service windowsystem textwidgets attica \
                bookmarks jobwidgets solid crash designerplugin    \
                archive doctools emoticons itemmodels init         \
                notifications parts unitconversion ecm i18n xmlgui \
                dbusaddons iconthemes kio sonnet kdelibs4support

.include "${.CURDIR}/../../x11/kde5-plasma/bsd.kde5-plasma.mk"
.include <bsd.port.mk>

