# Created by: Tobias Berner <tcberner@gmail.com>

PORTNAME=	ksshaskpass
CATEGORIES=	security # kde-framework
COMMENT=	KDE5 sshaskpass frontend

USE_QT5=	core
USE_KDE5=	coreaddons ecm i18n kdeprefix wallet widgetsaddons

.include "${.CURDIR}/../../x11/kde5-plasma/bsd.kde5-plasma.mk"
.include <bsd.port.mk>
