# Created by: Tobias Berner <tcberner@gmail.com>

PORTNAME=	kcoreaddons
CATEGORIES=	devel # kde-framework
COMMENT=	KDE5 coreaddons

USE_QT5=	core linguisttools
USE_KDE5=	ecm kdeprefix

# TODO: do this better
USES=		shared-mime-info cmake tar:xz

.include "${.CURDIR}/../../x11/kde5-frameworks/bsd.kde5-frameworks.mk"
.include <bsd.port.mk>
