# Created by: Tobias Berner <tcberner@gmail.com>

PORTNAME=	knewstuff 
CATEGORIES=	devel # kde-framework
COMMENT=	KDE5 newstuff

USE_QT5=        core gui widgets xml dbus network
USE_KDE5=       kdeprefix ecm archive completion config coreaddons \
                i18n auth codecs guiaddons configwidgets iconthemes\
                globalaccel dbusaddons service windowsystem sonnet \
                bookmarks jobwidgets solid kio itemviews textwidgets\
                widgetsaddons xmlgui attica

.include "${.CURDIR}/../../x11/kde5-frameworks/bsd.kde5-frameworks.mk"
.include <bsd.port.mk>
