# Created by: Tobias Berner <tcberner@gmail.com>

PORTNAME=       frameworks
PKGNAMEPREFIX?=	kde5-

CATEGORIES=     x11
PORTVERSION=	${KDE5_FRAMEWORKS_VERSION}

MAINTAINER=     kde@FreeBSD.org
COMMENT=        KDE5 frameworks meta port

USE_KDE5=       ${_USE_KDE5_FRAMEWORKS_ALL}

DISTFILES=	
NO_BUILD=       yes
NO_INSTALL=     yes
NO_MTREE=       yes

.include <bsd.port.mk>

