# Created by: Tobias Berner <tcberner@gmail.com>

PORTNAME=	knotifyconfig
CATEGORIES=	devel # kde-framework
COMMENT=	KDE5 notifyconfig

USE_QT5=        core gui widgets dbus xml network
USE_KDE5=       kdeprefix ecm completion config i18n coreaddons\
                auth codecs guiaddons itemviews iconthemes \
                globalaccel dbusaddons windowsystem sonnet \
                textwidgets attica bookmarks jobwidgets solid\
                kio service configwidgets notifications \
                widgetsaddons xmlgui

.include "${.CURDIR}/../../x11/kde5-frameworks/bsd.kde5-frameworks.mk"
.include <bsd.port.mk>
