# Created by: Tobias Berner <tcberner@gmail.com>

PORTNAME=	kxmlgui
CATEGORIES=	x11-toolkits # kde-framework
COMMENT=	KDE5 xml gui

USE_QT5=	core dbus gui network printsupport widgets xml
USE_KDE5=	attica auth codecs completion config configwidgets \
		coreaddons dbusaddons ecm globalaccel guiaddons \
		i18n iconthemes itemviews kdeprefix service sonnet \
		textwidgets widgetsaddons windowsystem

.include "${.CURDIR}/../../x11/kde5-frameworks/bsd.kde5-frameworks.mk"
.include <bsd.port.mk>
