# Created by: Tobias Berner <tcberner@gmail.com>

PORTNAME=	kservice 
CATEGORIES=	devel # kde-framework
COMMENT=	KDE5 service

USE_QT5=        core dbus xml gui widgets concurrent
USE_KDE5=       kdeprefix ecm config coreaddons windowsystem \
                crash dbusaddons i18n archive doctools
		
.include "${.CURDIR}/../../x11/kde5-frameworks/bsd.kde5-frameworks.mk"
.include <bsd.port.mk>
