# Created by: Tobias Berner <tcberner@gmail.com>

PORTNAME=	kservice 
CATEGORIES=	devel # kde-framework
COMMENT=	KDE5 service

USE_QT5=	concurrent core dbus gui widgets xml
USE_KDE5=	archive config coreaddons crash dbusaddons \
		doctools ecm i18n kdeprefix windowsystem

.include "${.CURDIR}/../../x11/kde5-frameworks/bsd.kde5-frameworks.mk"
.include <bsd.port.mk>
