# Created by: Tobias Berner <tcberner@gmail.com>

PORTNAME=	khelpcenter 
CATEGORIES=	sysutils # kde-plasma
COMMENT=	KDE5 khelpcenter 

USE_QT5=	core dbus gui network printsupport widgets xml
USE_KDE5=	archive attica auth bookmarks codecs completion config \
		configwidgets coreaddons crash dbusaddons designerplugin \
		doctools ecm emoticons globalaccel guiaddons i18n iconthemes \
		init itemmodels itemviews jobwidgets js kcmutils \
		kdelibs4support kdeprefix khtml kio notifications parts \
		service solid sonnet textwidgets unitconversion wallet \
		widgetsaddons windowsystem xmlgui

.include "${.CURDIR}/../../x11/kde5-plasma/bsd.kde5-plasma.mk"
.include <bsd.port.mk>

