# Created by: Tobias Berner <tcberner@gmail.com>

PORTNAME=       libkscreen
CATEGORIES=     x11 # kde-plasma
COMMENT=        KDE5 libkscreen 

USE_QT5=        core gui x11extras
USE_KDE5=       kdeprefix ecm
                
.include "${.CURDIR}/../../x11/kde5-plasma/bsd.kde5-plasma.mk"
.include <bsd.port.mk>

