# Created by: Tobias Berner <tcberner@gmail.com>

PORTNAME=	kitemmodels
CATEGORIES=	devel # kde-framework
COMMENT=	KDE5 itemmodels

USE_KDE5=	kdeprefix ecm
USE_QT5=	core dbus linguisttools
		
.include "${.CURDIR}/../../x11/kde5-frameworks/bsd.kde5-frameworks.mk"
.include <bsd.port.mk>
