# Created by: Tobias Berner <tcberner@gmail.com>

PORTNAME=	kitemmodels
CATEGORIES=	devel # kde-framework
COMMENT=	KDE5 itemmodels

USE_QT5=	core dbus linguisttools
USE_KDE5=	ecm kdeprefix

.include "${.CURDIR}/../../x11/kde5-frameworks/bsd.kde5-frameworks.mk"
.include <bsd.port.mk>
