# Created by: Tobias Berner <tcberner@gmail.com>

PORTNAME=	kcrash
CATEGORIES=	devel # kde-framework
COMMENT=	KDE5 crash

USE_QT5=	core gui widgets x11extras
USE_KDE5=	coreaddons ecm kdeprefix windowsystem

.include "${.CURDIR}/../../x11/kde5-frameworks/bsd.kde5-frameworks.mk"
.include <bsd.port.mk>
