# Created by: Tobias Berner <tcberner@gmail.com>

PORTNAME=	kcrash 
CATEGORIES=	devel # kde-framework
COMMENT=	KDE5 crash

USE_QT5=        core gui x11extras widgets
USE_KDE5=       kdeprefix ecm coreaddons windowsystem
		
.include "${.CURDIR}/../../x11/kde5-frameworks/bsd.kde5-frameworks.mk"
.include <bsd.port.mk>
