# Created by: Tobias Berner <tcberner@gmail.com>

PORTNAME=	kitemviews
CATEGORIES=	x11-toolkits # kde-framework
COMMENT=	KDE5 itemviews

USE_QT5=        core gui widgets linguisttools
USE_KDE5=       kdeprefix ecm
		
.include "${.CURDIR}/../../x11/kde5-frameworks/bsd.kde5-frameworks.mk"
.include <bsd.port.mk>
