# Created by: Tobias Berner <tcberner@gmail.com>

PORTNAME=	kitemviews
CATEGORIES=	x11-toolkits # kde-framework
COMMENT=	KDE5 itemviews

USE_QT5=	core gui linguisttools widgets
USE_KDE5=	ecm kdeprefix

OPTIONS_DEFINE=	NLS
OPTIONS_SUB=	YES

.include "${.CURDIR}/../../x11/kde5-frameworks/bsd.kde5-frameworks.mk"
.include <bsd.port.mk>
