# Created by: Tobias Berner <tcberner@gmail.com>

PORTNAME=       kwrited
CATEGORIES=     devel # kde-plasma
COMMENT=        KDE5 kwrited 

USE_QT5=        xml gui widgets dbus network printsupport core
USE_KDE5=       kdeprefix coreaddons i18n auth codecs config guiaddons \
                widgetsaddons configwidgets windowsystem crash         \
                designerplugin archive doctools dbusaddons service     \
                emoticons itemviews iconthemes itemmodels init         \
                notifications globalaccel completion sonnet            \
                textwidgets attica xmlgui bookmarks jobwidgets solid   \
                kio parts unitconversion kdelibs4support ecm pty 
                
.include "${.CURDIR}/../../x11/kde5-plasma/bsd.kde5-plasma.mk"
.include <bsd.port.mk>

