# Created by: Tobias Berner <tcberner@gmail.com>

PORTNAME=	kwindowsystem
CATEGORIES=	x11 # kde-framework
COMMENT=	KDE5 windowsystem

USE_QT5=        core gui widgets x11extras linguisttools
USE_KDE5=       kdeprefix ecm

.include "${.CURDIR}/../../x11/kde5-frameworks/bsd.kde5-frameworks.mk"
.include <bsd.port.mk>
