# Created by: Tobias Berner <tcberner@gmail.com>

PORTNAME=	kdeplasma-addons
CATEGORIES=	x11-toolkits # kde-framework
COMMENT=	KDE5 plasma addons

USE_QT5=        core gui widgets linguisttools uitools
USE_KDE5=       kdeprefix ecm declarative

USES=		cmake:outsource tar:xz
		
.include "${.CURDIR}/../../x11/kde5-plasma/bsd.kde5-plasma.mk"
.include <bsd.port.mk>
