# Created by: Tobias Berner <tcberner@gmail.com>

PORTNAME=	plasma-workspace-wallpapers
CATEGORIES=	x11-themes # kde-framework
COMMENT=	KDE5 plasma addons

USE_QT5=	core gui linguisttools uitools widgets
USE_KDE5=	declarative ecm kdeprefix

.include "${.CURDIR}/../../x11/kde5-plasma/bsd.kde5-plasma.mk"
.include <bsd.port.mk>
