# Created by: Tobias Berner <tcberner@gmail.com>

PORTNAME=	kunitconversion
CATEGORIES=	devel # kde-framework
COMMENT=	KDE5 unit conversion

USE_QT5=        core xml network
USE_KDE5=       kdeprefix ecm i18n
		
.include "${.CURDIR}/../../x11/kde5-frameworks/bsd.kde5-frameworks.mk"
.include <bsd.port.mk>
