# Created by: Tobias Berner <tcberner@gmail.com>

PORTNAME=	kunitconversion
CATEGORIES=	devel # kde-framework
COMMENT=	KDE5 unit conversion

USE_QT5=	core network xml
USE_KDE5=	ecm i18n kdeprefix

OPTIONS_DEFINE=	NLS
OPTIONS_SUB=	YES

.include "${.CURDIR}/../../x11/kde5-frameworks/bsd.kde5-frameworks.mk"
.include <bsd.port.mk>
