# Created by: Tobias Berner <tcberner@gmail.com>

PORTNAME=	kconfig 
CATEGORIES=	devel # kde-framework
COMMENT=	KDE5 configuration framework

USE_QT5=        gui xml core linguisttools
USE_KDE5=       kdeprefix ecm
		
.include "${.CURDIR}/../../x11/kde5-frameworks/bsd.kde5-frameworks.mk"
.include <bsd.port.mk>
