# Created by: Tobias Berner <tcberner@gmail.com>

PORTNAME=	kconfig
CATEGORIES=	devel # kde-framework
COMMENT=	KDE5 configuration framework

USE_QT5=	core gui linguisttools xml
USE_KDE5=	ecm kdeprefix

OPTIONS_DEFINE=	NLS
OPTIONS_SUB=	YES

.include "${.CURDIR}/../../x11/kde5-frameworks/bsd.kde5-frameworks.mk"
.include <bsd.port.mk>
