# Created by: Tobias Berner <tcberner@gmail.com>

PORTNAME=	kinit
CATEGORIES=	x11 # kde-framework
COMMENT=	KDE5 kdeinit

USE_QT5=	core
USE_KDE5=	ecm kdeprefix kio service

OPTIONS_DEFINE=	DOCS NLS
OPTIONS_SUB=	YES

.include "${.CURDIR}/../../x11/kde5-frameworks/bsd.kde5-frameworks.mk"
.include <bsd.port.mk>
