# Created by: Tobias Berner <tcberner@gmail.com>

PORTNAME=	ki18n 
CATEGORIES=	devel # kde-framework
COMMENT=	KDE5 i18n 

USE_QT5=        core script concurrent
USE_KDE5=       kdeprefix ecm
		
.include "${.CURDIR}/../../x11/kde5-frameworks/bsd.kde5-frameworks.mk"
.include <bsd.port.mk>
