# Created by: Tobias Berner <tcberner@gmail.com>

PORTNAME=	ki18n
CATEGORIES=	devel # kde-framework
COMMENT=	KDE5 i18n

USE_QT5=	concurrent core script
USE_KDE5=	ecm kdeprefix

.include "${.CURDIR}/../../x11/kde5-frameworks/bsd.kde5-frameworks.mk"
.include <bsd.port.mk>
