# Created by: Tobias Berner <tcberner@gmail.com>

PORTNAME=	kimageformats
CATEGORIES=	graphics # kde-framework
COMMENT=	KDE5 image formats

LIB_DEPENDS=	libIlmImf.so:${PORTSDIR}/graphics/OpenEXR

USE_QT5=	core gui printsupport widgets
USE_KDE5=	ecm kdeprefix

.include "${.CURDIR}/../../x11/kde5-frameworks/bsd.kde5-frameworks.mk"
.include <bsd.port.mk>
