# Created by: Tobias Berner <tcberner@gmail.com>

PORTNAME=	kimageformats
CATEGORIES=	graphics # kde-framework
COMMENT=	KDE5 image formats

USE_QT5=        widgets printsupport core gui
USE_KDE5=       kdeprefix ecm
		
.include "${.CURDIR}/../../x11/kde5-frameworks/bsd.kde5-frameworks.mk"
.include <bsd.port.mk>
