# Created by: Tobias Berner <tcberner@gmail.com>

PORTNAME=	oxygen-fonts
CATEGORIES=	x11-fonts # kde-plasma
COMMENT=	KDE5 oxygen-fonts 

BUILD_DEPENDS=	fontforge:${PORTSDIR}/print/fontforge

USE_QT5=	core
USE_KDE5=	ecm kdeprefix

.include "${.CURDIR}/../../x11/kde5-plasma/bsd.kde5-plasma.mk"
.include <bsd.port.mk>

