# Created by: Tobias Berner <tcberner@gmail.com>

PORTNAME=       oxygen-fonts
CATEGORIES=     x11-fonts # kde-plasma
BUILD_DEPENDS=	${LOCALBASE}/bin/fontforge:${PORTSDIR}/print/fontforge
COMMENT=        KDE5 oxygen-fonts 

USE_QT5=        core
USE_KDE5=       kdeprefix ecm
                
.include "${.CURDIR}/../../x11/kde5-plasma/bsd.kde5-plasma.mk"
.include <bsd.port.mk>

