# Created by: Tobias Berner <tcberner@gmail.com>

PORTNAME=	kcmutils
CATEGORIES=	devel # kde-framework
COMMENT=	KDE5 kcmutils

USE_QT5=        core gui widgets dbus xml
USE_KDE5=       kdeprefix ecm itemviews auth codecs config guiaddons \
                widgetsaddons configwidgets coreaddons i18n iconthemes  \
                dbusaddons service globalaccel completion windowsystem \
                sonnet textwidgets attica xmlgui
		
.include "${.CURDIR}/../../x11/kde5-frameworks/bsd.kde5-frameworks.mk"
.include <bsd.port.mk>
