# Created by: Tobias Berner <tcberner@gmail.com> 

PORTNAME=	kdoctools 
CATEGORIES=	devel # kde-framework
COMMENT=	KDE5 doctools

USE_QT5=	core
USE_KDE5=	archive ecm i18n kdeprefix
USE_GNOME=	libxml2 libxslt

.include "${.CURDIR}/../../x11/kde5-frameworks/bsd.kde5-frameworks.mk"
.include <bsd.port.mk>
