# Created by: Tobias Berner <tcberner@gmail.com>
# $FreeBSD: ports/devel/kde5-kconfig/Makefile,v 1.6 2014/07/16c 18:48:25 makc Exp $

PORTNAME=	kdoctools 
CATEGORIES=	devel # kde-framework
COMMENT=	KDE5 doctools

USE_QT5=        core
USE_KDE5=       kdeprefix ecm
		
.include "${.CURDIR}/../../x11/kde5-frameworks/bsd.kde5-frameworks.mk"
.include <bsd.port.mk>
