# Created by: Tobias Berner <tcberner@gmail.com>

PORTNAME=	kdecoration
CATEGORIES=	x11-wm # kde-plasma
COMMENT=	KDE5 kdecoration

USE_QT5=	core gui
USE_KDE5=	ecm kdeprefix

.include "${.CURDIR}/../../x11/kde5-plasma/bsd.kde5-plasma.mk"
.include <bsd.port.mk>

