# Created by: Tobias Berner <tcberner@gmail.com>

PORTNAME=	kcodecs
CATEGORIES=	textproc # kde-framework
COMMENT=	KDE5 codecs

USE_QT5=	core linguisttools
USE_KDE5=	ecm kdeprefix

.include "${.CURDIR}/../../x11/kde5-frameworks/bsd.kde5-frameworks.mk"
.include <bsd.port.mk>
