# Created by: Tobias Berner <tcberner@gmail.com>

PORTNAME=	kbookmarks
CATEGORIES=	devel # kde-frameworks
COMMENT=	KDE5 dbus addons

USE_QT5=	core dbus gui linguisttools widgets xml
USE_KDE5=	attica auth codecs completion config configwidgets coreaddons \
		dbusaddons ecm globalaccel guiaddons i18n iconthemes \
		itemviews kdeprefix service sonnet textwidgets widgetsaddons \
		windowsystem xmlgui

.include "${.CURDIR}/../../x11/kde5-frameworks/bsd.kde5-frameworks.mk"
.include <bsd.port.mk>
