# Created by: Tobias Berner <tcberner@gmail.com>

PORTNAME=	kbookmarks
CATEGORIES=	devel # kde-frameworks
COMMENT=	KDE5 dbus addons

USE_QT5=        core gui widgets xml dbus linguisttools
USE_KDE5=       kdeprefix ecm auth codecs config guiaddons i18n \
		configwidgets coreaddons itemviews iconthemes \
                widgetsaddons globalaccel completion dbusaddons \
	        service windowsystem sonnet textwidgets attica xmlgui
		
.include "${.CURDIR}/../../x11/kde5-frameworks/bsd.kde5-frameworks.mk"
.include <bsd.port.mk>
