# Created by: Tobias Berner <tcberner@gmail.com>

PORTNAME=	kplotting
CATEGORIES=	graphics # kde-framework
COMMENT=	KDE5 plotting

USE_QT5=        core gui widgets
USE_KDE5=       kdeprefix ecm
		
.include "${.CURDIR}/../../x11/kde5-frameworks/bsd.kde5-frameworks.mk"
.include <bsd.port.mk>
