# Created by: Tobias Berner <tcberner@gmail.com>

PORTNAME=	kde-gtk-config
PORTVERSION=	${KDE5_VERSION}
CATEGORIES=	x11-themes # kde-plasma
COMMENT=	KDE5 gtk config 

USE_GNOME=	gtk20 gtk30 glib20 
USE_QT5=	core widgets
USE_KDE5=	archive configwidgets ecm i18n kcmutils kdeprefix newstuff

.include "${.CURDIR}/../../x11/kde5-plasma/bsd.kde5-plasma.mk"
.include <bsd.port.mk>

