# Created by: Tobias Berner <tcberner@gmail.com>

PORTNAME=	kiconthemes
CATEGORIES=	x11-themes # kde-framework
COMMENT=	KDE5 icon themes

USE_QT5=        core gui widgets svg dbus xml
USE_KDE5=       kdeprefix ecm i18n coreaddons auth codecs \
		config guiaddons configwidgets widgetsaddons \
		itemviews
		
.include "${.CURDIR}/../../x11/kde5-frameworks/bsd.kde5-frameworks.mk"
.include <bsd.port.mk>
