# Created by: Tobias Berner <tcberner@gmail.com>

PORTNAME=	kiconthemes
CATEGORIES=	x11-themes # kde-framework
COMMENT=	KDE5 icon themes

USE_QT5=	concurrent core script svg widgets
USE_KDE5=	configwidgets ecm i18n itemviews kdeprefix

.include "${.CURDIR}/../../x11/kde5-frameworks/bsd.kde5-frameworks.mk"
.include <bsd.port.mk>
