# Created by: Tobias Berner <tcberner@gmail.com>

PORTNAME=       breeze
PORTVERSION=    ${KDE5_VERSION}

CATEGORIES=     x11-themes # kde-plasma
COMMENT=        KDE5 breeze 

USE_QT5=        xml core gui widgets
USE_KDE5=       kdeprefix ecm coreaddons config frameworkintegration
                
.include "${.CURDIR}/../../x11/kde5-plasma/bsd.kde5-plasma.mk"
.include <bsd.port.mk>

