# Created by: Tobias Berner <tcberner@gmail.com>

PORTNAME=	breeze
PORTVERSION=	${KDE5_VERSION}

CATEGORIES=	x11-themes # kde-plasma
COMMENT=	KDE5 breeze

USE_QT5=	core gui widgets xml
USE_KDE5=	config coreaddons decoration ecm frameworkintegration kdeprefix

OPTIONS_DEFINE=	NLS
OPTIONS_SUB=	YES

.include "${.CURDIR}/../../x11/kde5-plasma/bsd.kde5-plasma.mk"
.include <bsd.port.mk>

