# Created by: Tobias Berner <tcberner@gmail.com>

PORTNAME=	kjsembed
CATEGORIES=	www # kde-framework
COMMENT=	KDE5 jsembed
MASTER_SITE_SUBDIR?=    stable/frameworks/${KDE5_FRAMEWORKS_VERSION:R}/portingAids

USE_QT5=        core uitools gui widgets xml svg
USE_KDE5=       kdeprefix ecm js i18n archive doctools

.include "${.CURDIR}/../../x11/kde5-frameworks/bsd.kde5-frameworks.mk"
.include <bsd.port.mk>
