# Created by: Tobias Berner <tcberner@gmail.com>

PORTNAME=	kwallet
CATEGORIES=	sysutils # kde-framework
COMMENT=	KDE5 dbus addons

USE_QT5=        core gui xml widgets dbus
USE_KDE5=       kdeprefix ecm config dbusaddons service windowsystem \
                notifications coreaddons i18n auth codecs guiaddons \
                configwidgets itemviews iconthemes widgetsaddons		

.include "${.CURDIR}/../../x11/kde5-frameworks/bsd.kde5-frameworks.mk"
.include <bsd.port.mk>
